apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: reqap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard   # replace with SSD StorageClass for better throughput
